Cleanup click usage and add support for config defaults from file
tcorbettclark/encapsia-cli pull request #41
Opened 2020-09-14 15:45 UTC by tcorbettclark

* Tidied use of Click to be aligned with click docs / best practice.
* All command line options can now be provided either as env vars or from a `~/.encapsia/config.toml` file.
* Created that config file if missing and add explanatory docs.

Planning for this to be a version 0.3.0.

2020-09-14 17:18 UTC, petrem requested changes
Please address the `from pathlib import Path` comment at a minimum.

2020-09-14 17:18 UTC, petrem commented on encapsia_cli/plugins.py
> +import pathlib
Stop importing it as `from pathlib import Path`, below.

2020-09-14 17:18 UTC, petrem commented on encapsia_cli/plugins.py
> +    filename = Path(plugins_local_dir, pi.get_filename())
`pathlib.Path`

2020-09-14 17:18 UTC, petrem commented on encapsia_cli/plugins.py
>      DEV_VERSION_REGEX = re.compile(r"([0-9]+)\.([0-9]+)\.([0-9]+)dev([0-9]+)")
Shoudn't we allow more flexible pre-release and build components?

2020-09-14 17:18 UTC, petrem commented on encapsia_cli/plugins.py
> +        else:
You could drop the `else`.

2020-09-14 17:18 UTC, petrem commented on encapsia_cli/plugins.py
> +        tmp = []
suggest rename to e.g. `plugin_infos`

2020-09-15 08:09 UTC, tcorbettclark commented on CHANGELOG.md
> +- Changed `encapsia httpie shell` to `encapsia httpie` because it can only launch interactive httpie.
I think you can redirect to/from file, but I always end up looking it up every time!

2020-09-15 08:09 UTC, tcorbettclark commented on CHANGELOG.md
> +- Moved the `--host` option to the top level. So e.g. `encapsia users --host foo` is now `encapsia --host foo users`.
:-)

2020-09-15 08:09 UTC, tcorbettclark commented on CHANGELOG.md
> +- Added uniform support for providing options as env vars following click conventions. E.g.
Good!

2020-09-15 08:10 UTC, tcorbettclark commented on encapsia_cli/encapsia.py
> +        with filename.open("w") as f:
Module level constant sounds good. I'll do that.

2020-09-15 08:14 UTC, tcorbettclark commented on encapsia_cli/encapsia.py
> +    filename = pathlib.Path("~/.encapsia/config.toml").expanduser()
Yup, that's better.

2020-09-15 08:15 UTC, tcorbettclark commented on encapsia_cli/encapsia.py
> +    filename = pathlib.Path("~/.encapsia/config.toml").expanduser()
Better still: `filename = pathlib.Path.home() / ".encapsia" / "config.toml"`

2020-09-15 08:19 UTC, tcorbettclark commented on encapsia_cli/plugins.py
> +import pathlib
Done.

2020-09-15 08:20 UTC, tcorbettclark commented on encapsia_cli/plugins.py
>      DEV_VERSION_REGEX = re.compile(r"([0-9]+)\.([0-9]+)\.([0-9]+)dev([0-9]+)")
I think we shouldn't even allow these types of tags. Semver only. These are for backwards compatibility in order to support the versions we currently have for plugins in S3 `ice-plugins`. The output from the command kind of hints that it is being nice by converting for you, implying that semver would have been easier...

2020-09-15 08:23 UTC, tcorbettclark commented on encapsia_cli/plugins.py
> +        else:
Could do :-)

My general preference is to avoid early drop-outs from functions unless there are several and it is therefore obvious what is happening.

I'm going to turn it around to sanitise the input first, and then otherwise always return:
```python
    @classmethod
    def make_from_filename(cls, filename):
        m = cls.PLUGIN_REGEX.match(str(filename))
        if m is None:
            raise ValueError(f"Unable to parse: {filename}")
        return cls.make_from_name_version(m.group(1), m.group(2))
```

2020-09-15 08:25 UTC, tcorbettclark commented on encapsia_cli/plugins.py
> +        tmp = []
Done

2020-09-15 08:44 UTC, tcorbettclark commented on encapsia_cli/encapsia.py
> +    for d in ["plugins-local-dir"]:
Good spot. That's wrong now. Fixing...

2020-09-15 08:50 UTC, tcorbettclark commented on encapsia_cli/encapsia.py
> +    ctx.color = {"always": True, "never": False, "auto": None}[colour]
OK

2020-09-15 08:50 UTC, tcorbettclark commented on encapsia_cli/encapsia.py
> +    for d in ["plugins-local-dir"]:
In fact, removing it. The coercing to pathlib.Path can happen in `plugins.py:main` now.

2020-09-15 08:51 UTC, petrem commented on encapsia_cli/plugins.py
>      DEV_VERSION_REGEX = re.compile(r"([0-9]+)\.([0-9]+)\.([0-9]+)dev([0-9]+)")
I am not referring to the fourth dot-number. Semver allows for pre-release and build components, what you do in (`DEV_VERSION_REGEX`). But it seems this only allows `1.2.3dev4`. I might have guessed wrong the usage of these.
Semver would look like `1.2.3-dev.1`, `1.2.3-foo.bar.2` and possibly with a build metadata `1.2.3-dev+g4532dee3`.

2020-09-15 09:02 UTC, petrem approved these changes

2020-09-15 09:02 UTC, petrem commented on encapsia_cli/plugins.py
> +    filename = Path(plugins_local_dir, pi.get_filename())
While using Click, I think I would have preferred `import pathlib` and `pathlib.Path(...)` -- as you do in other files -- to clearly distinguish from `click.Path()`. But this isn't an important change, as long as it is now consistently used within the module. Marking unresolved just for "ping" -- please decide.

2020-09-15 09:10 UTC, tcorbettclark commented on encapsia_cli/plugins.py
>      DEV_VERSION_REGEX = re.compile(r"([0-9]+)\.([0-9]+)\.([0-9]+)dev([0-9]+)")
The `semver` handles proper semver. These regex's are just to handle the incorrect versions like `1.2.3.4` and the dev version which doesn't mean what you think it should mean under semver!

2020-09-15 10:07 UTC, merged