Issue-#79: changed pluginsmanager method
tcorbettclark/encapsia-cli pull request #88
Opened 2022-08-30 13:26 UTC by atofei

Installed_plugins_with_tags() is deprecated in favor of plugins() function.

2022-08-31 09:57 UTC, petrem commented
The new SQL in PluginsManager function returns slightly different fields, you will have to account for the differences.

For example, you are missing the tags (scroll to the right):

```text
> poetry run encapsia --host localhost plugins status --long
name*          version**    available**    installed                 description                                         plugin-tags
-------------  -----------  -------------  ------------------------  --------------------------------------------------  -------------
datapointslib  1.1.0        <same>         Wed 31 Aug 2022 09:42:45  Library to obtain 'tall thin' table of datapoints.
manager        2.0.0-44     <same>         Wed 31 Aug 2022 09:35:32  Manager app
tutor          1.1.9-8      <same>         Wed 31 Aug 2022 09:35:48  Tutor app
```

whereas the original version shows them:

```text
 > el plugins status --long
name*          version**    available**    installed                 description                                         plugin-tags
-------------  -----------  -------------  ------------------------  --------------------------------------------------  -------------
datapointslib  1.1.0        <same>         Wed 31 Aug 2022 09:42:45  Library to obtain 'tall thin' table of datapoints.  middleware
manager        2.0.0-44     <same>         Wed 31 Aug 2022 09:35:32  Manager app                                         tutor-enabled
tutor          1.1.9-8      <same>         Wed 31 Aug 2022 09:35:48  Tutor app
```

Another place where this would be visible is `freeze` if you have plugins with "variants" installed, and probably in the install `install` sub-command too.

The new `plugins()` SQL function returns a record with a field `manifest` that contains the plugin manifest, including the tags, as a JSON object. You'll want to use this instead of the `plugin_tags` field that is returned by the orginal call, which is not present in the new API.

2022-08-31 10:02 UTC, petrem requested changes
The new SQL in PluginsManager function returns slightly different fields, you will have to account for the differences.

For example, you are missing the tags (scroll to the right):

```text
> poetry run encapsia --host localhost plugins status --long
name*          version**    available**    installed                 description                                         plugin-tags
-------------  -----------  -------------  ------------------------  --------------------------------------------------  -------------
datapointslib  1.1.0        <same>         Wed 31 Aug 2022 09:42:45  Library to obtain 'tall thin' table of datapoints.
manager        2.0.0-44     <same>         Wed 31 Aug 2022 09:35:32  Manager app
tutor          1.1.9-8      <same>         Wed 31 Aug 2022 09:35:48  Tutor app
```

whereas the original version shows them:

```text
 > el plugins status --long
name*          version**    available**    installed                 description                                         plugin-tags
-------------  -----------  -------------  ------------------------  --------------------------------------------------  -------------
datapointslib  1.1.0        <same>         Wed 31 Aug 2022 09:42:45  Library to obtain 'tall thin' table of datapoints.  middleware
manager        2.0.0-44     <same>         Wed 31 Aug 2022 09:35:32  Manager app                                         tutor-enabled
tutor          1.1.9-8      <same>         Wed 31 Aug 2022 09:35:48  Tutor app
```

Another place where this would be visible is `freeze` if you have plugins with "variants" installed, and probably in the install `install` sub-command too.

The new `plugins()` SQL function returns a record with a field `manifest` that contains the plugin manifest, including the tags, as a JSON object. You'll want to use this instead of the `plugin_tags` field that is returned by the orginal call, which is not present in the new API.

2022-09-02 09:13 UTC, atofei commented
thanks, updated.

2022-09-02 10:55 UTC, petrem approved these changes

2022-09-02 10:59 UTC, merged