Installing and adding to local_store groups of plugins with one command
tcorbettclark/encapsia-cli pull request #90
Opened 2022-09-05 19:20 UTC by pocroianu

Fixes #87

Tested using:

`encapsia plugins --s3-bucket=encapsia-plugins/cmedtech/pd/production/insights/ --s3-bucket encapsia-plugins/cmedcro/standards/production/insights install`

`encapsia plugins --s3-bucket=encapsia-plugins/cmedtech/pd/production/insights/ --s3-bucket encapsia-plugins/cmedcro/standards/production/insights add`

2022-09-07 06:19 UTC, petrem requested changes
1. Please adhere to coding standards. Please read the README file, and run the style/lint and test commands, as a minimum.
2. I think it's a bad idea to have the command assume it should add all plugins if I specify the `--s3-bucket` option. It's unexpected for the user, and I see no benefit. I'd rather have a new option e.g. `--all-from-s3` or `--latest-in-s3` that needs to be given explicitly.
3. Make an explicit list of specs of `exact_match`ing `PluginSpec`s, and we can probably avoid the "from_s3" flag.

2022-09-08 08:26 UTC, pocroianu commented on encapsia_cli/plugins.py
> +import os
Removed import. No longer needed

2022-09-08 08:26 UTC, pocroianu commented on encapsia_cli/plugins.py
> +    default=[
Reverted to the default list.

2022-09-08 08:26 UTC, pocroianu commented on encapsia_cli/plugins.py
> +def _add_to_temp_store_from_s3(
2. They are to the local_store now.

2022-09-08 08:27 UTC, pocroianu commented on encapsia_cli/plugins.py
> +    default_values_dict = dict(zip([command.name for command in ctx.command.params], [command.default for command in ctx.command.params]))
Removed this part as it's no longer needed.

2022-09-08 12:58 UTC, petrem commented on encapsia_cli/plugins.py
> +    plugins_s3_buckets_from_input = obj["plugins_s3_buckets_from_input"]
I think this is left-over code from previous version, right? As is the bit below.

2022-09-08 15:24 UTC, pocroianu commented on encapsia_cli/plugins.py
> +    plugins_s3_buckets_from_input = obj["plugins_s3_buckets_from_input"]
Yeah. Addressed that.

2022-09-08 17:02 UTC, petrem commented on encapsia_cli/plugins.py
> +        to_download_from_s3 = PluginInfos.make_from_s3_buckets(plugins_s3_buckets)
Why do you need to do this separately here, and not append them to `to_download_from_s3` and let it do the same thing with the existing code below?

2022-09-08 17:02 UTC, petrem commented on encapsia_cli/plugins.py
> +
is this new empty line added on purpose? i don't think it's so necessary here

2022-09-09 07:04 UTC, pocroianu commented on encapsia_cli/plugins.py
> +        to_download_from_s3 = PluginInfos.make_from_s3_buckets(plugins_s3_buckets)
If it will download all the available plugins on s3, I don't think there is any point to check the TOML config, or getting the latest version of each plugin or parsing the `plugins` because it will contain all of them anyway. I was mainly thinking it would be more optimal this way :)

2022-09-09 07:06 UTC, pocroianu commented on encapsia_cli/plugins.py
> +
Mainly for visibility.

2022-09-12 13:57 UTC, petrem approved these changes

2022-09-12 14:02 UTC, merged