Fixed installing plugin from file path
tcorbettclark/encapsia-cli pull request #91
Opened 2022-09-06 14:42 UTC by pocroianu

Fixes #76 

For use-case 1 https://github.com/tcorbettclark/encapsia-cli/issues/76#issue-943217796: it was trying to add a `PluginInfo` instead of a `PluginSpec` to the `to_install_candidates` list.

For use-case 2 https://github.com/tcorbettclark/encapsia-cli/issues/76#issuecomment-922670138: Added a check that verifies if the plugin string is in fact a file_path before trying to add it to the local_store.
If it is a file_path, but the file (plugin) doesn't exist, it will skip it. (perhaps a log that says "The plugin path is not valid. The file doesn't exist" would be good to add there)

2022-09-07 07:48 UTC, petrem requested changes

2022-09-07 07:48 UTC, petrem commented on encapsia_cli/plugininfo.py
> +        m = cls.PATH_REGEX.match(spec_string)
i suggest
```python
return cls.PATH_REGEX.match(spec_string) is not None
```

2022-09-07 07:48 UTC, petrem commented on encapsia_cli/plugins.py
> +        # Check if string is a path to a plugin
Minor: If the name of the method would be more self-evident, e.g. `PluginInfo.looks_like_path_to_plugin`, or something, the comment pointless (a good thing).

2022-09-07 07:48 UTC, petrem commented on encapsia_cli/plugins.py
> +                # Need to add a plugin_spec in list below
I don't think this comment adds -- I think it's evident.

2022-09-07 07:48 UTC, petrem commented on encapsia_cli/plugininfo.py
> +    PATH_REGEX: T.ClassVar[re.Pattern] = re.compile(
`PLUGIN_PATH_REGEX`? more self-descriptive?

If the type annotation is useful here, please add it to the regular expressions above, too. So either everywhere or not at all, please.

2022-09-07 07:48 UTC, petrem commented on encapsia_cli/plugininfo.py
> +DIR_FORMAT = "[A-z0-9-_+]*/"
I think this is way too limiting. I think the test should be reversed: if it exists as a file, then take the filename (`Path(thing).name`) and make sure it looks like a plugin file name.

2022-09-07 07:48 UTC, petrem commented on walkthrough_tests/plugins.sh
> +test "Install a plugin using an absolute path"
Please rename "dir" to something more telling, like "example-plugins" or "test-plugins".

I'm not sure the "install using absolute path" is really that useful as a walk-through test. If it was a unit test, ok, but as it is, not so much. These tests are not a replacement for real testing. And I'd expect the second installation to hang asking you for interactive confirmation (as it is a re-install), without the `--force` flag. But all in all a path should be a path should be a path, absolute or otherwise.

2022-09-07 12:06 UTC, pocroianu commented on encapsia_cli/plugininfo.py
> +        m = cls.PATH_REGEX.match(spec_string)
Good point. Done.

2022-09-07 12:07 UTC, pocroianu commented on encapsia_cli/plugins.py
> +        # Check if string is a path to a plugin
Good point. Renamed to `PluginInfo.looks_like_path_to_plugin`. It sounds good as a method name :)

2022-09-07 12:08 UTC, pocroianu commented on encapsia_cli/plugins.py
> +                # Need to add a plugin_spec in list below
Removed.

2022-09-07 12:14 UTC, pocroianu commented on encapsia_cli/plugininfo.py
> +DIR_FORMAT = "[A-z0-9-_+]*/"
Made it a little less restrictive. In my opinion, it should first check if the plugin string looks like a path to a plugin, because we don't want to pass a plugin path instead of a plugin spec

2022-09-07 12:15 UTC, pocroianu commented on walkthrough_tests/plugins.sh
> +test "Install a plugin using an absolute path"
Renamed "dir" to "example_plugins" and removed the "install using absolute path". Added the `--force` flag to the walkthrough test.

2022-09-07 15:12 UTC, petrem commented on walkthrough_tests/plugins.sh
> +test "Install a plugin using an absolute path"
`--force` would be useful only the second time you install the plugin. Just run the steps and see for yourself :)

2022-09-07 15:31 UTC, petrem approved these changes

2022-09-07 15:31 UTC, petrem commented on encapsia_cli/plugins.py
> +                    f"Could not find a plugin matching the path: {plugin}!"
Maybe: "Requested plugin '{plugin}', which looks like a path to a file, but it does not exist"?
The point being to say we interpreted the argument as a file and could not find it.

2022-09-07 15:31 UTC, petrem commented on walkthrough_tests/plugins.sh
> +encapsia plugins --force install example_plugins/plugin-foo-1.0.0.tar.gz
I would expect `--force` is not necessary when installing it the first time. Maybe you need it to avoid the prompt? Please make sure it is needed.

2022-09-08 06:57 UTC, pocroianu commented on walkthrough_tests/plugins.sh
> +encapsia plugins --force install example_plugins/plugin-foo-1.0.0.tar.gz
Yes. Usually `encapsia plugins install` gives you a prompt "Y/N" if it finds plugins to install.

2022-09-08 06:58 UTC, pocroianu commented on walkthrough_tests/plugins.sh
> +test "Install a plugin using an absolute path"
Well, actually without `--force`, it gives you a prompt "Y/N". Without it the test comes to a "halt" :)

2022-09-08 07:00 UTC, pocroianu commented on encapsia_cli/plugins.py
> +                    f"Could not find a plugin matching the path: {plugin}!"
Yes. Good point. How about "The requested plugin '{plugin}', which looks like a path to a file, was not found" ?

2022-09-08 07:44 UTC, petrem commented on encapsia_cli/plugins.py
> +                    f"Could not find a plugin matching the path: {plugin}!"
Sounds good!

2022-09-08 08:31 UTC, pocroianu commented on encapsia_cli/plugins.py
> +                    f"Could not find a plugin matching the path: {plugin}!"
Done. Thank you

2022-09-08 11:50 UTC, merged