install will add to local store (from S3) when requested plugin not p…
tcorbettclark/encapsia-cli pull request #98
Opened 2022-11-21 16:41 UTC by mpopetcmed

2022-11-22 11:05 UTC, petrem requested changes

2022-11-22 11:36 UTC, mpopetcmed commented on encapsia_cli/plugins.py
> +            action = "download from s3 and " + action
I think it's important to have the download step described in the plan before user approving.

Tests can be updated, after all

2022-11-22 12:50 UTC, petrem commented on encapsia_cli/plugins.py
> +            action = "download from s3 and " + action
We already add to local store, without it being mentioned in the plan, for individually listed plugins as files and when installing all available buckets. So either way, it should be uniform (show just "install" or "add and install" -- in the first case mentioned about it  is not from S3 )

I've checked a bit, I did not find tests using this output in various plugins, at a brief search. So hopefully such a change wouldn't break existing tests. Updating them can be problematic.

2022-11-23 09:56 UTC, petrem commented on encapsia_cli/plugins.py
> +            action = "download from s3 and " + action
agreed to go ahead as is for now. we'll need to add other changes / refactoring so for now this is good enough.

2022-11-23 09:57 UTC, merged

2022-12-06 19:35 UTC, petrem commented
fixes #95